version: "3.7"

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: "library/postgres:12.4"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - foodgram/.env
  web:
    container_name: foodgram
    image: "39a785f638b7/foodgram:v1"
    build: .
    restart: always
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - foodgram/.env
    volumes:
      - static_volume:/code/recipes/static
    expose:
      - 8000
  nginx:
    build: ./nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - static_volume:/code/static
