# Generated by Django 3.0.7 on 2020-10-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20201004_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя в шаблоне'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='style',
            field=models.CharField(max_length=50, verbose_name='Цвет в шаблоне'),
        ),
    ]
