# Generated by Django 3.0.7 on 2020-10-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20201007_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.Tag'),
        ),
    ]
